resolver: lts-15.2
packages:
- '.'
extra-deps:
- '../massiv/'
- Color-0.1.4
- github: lehins/massiv-io
  commit: HEAD
  subdirs:
    - massiv-io
flags: {}
extra-package-dbs: []
nix:
  packages: [ zlib libGLU ]
