resolver: lts-10.0
packages:
  - '.'
  - '../massiv/'
  - '../massiv-io/'
  - '../../yarr/yarr-benchmarking'
  - '../../yarr/yarr-image-io'
  - '../../yarr/yarr'
extra-deps:
  - repa-3.4.1.3
  - repa-algorithms-3.4.1.2
  - fixed-vector-0.8.1.0
